### ISSUE TITLE
`legalIdentifier` should be `registryCode`

### ISSUE THREAD

**Issue by kvakes** [windingtree/org.json-schema#7]
In ORG.JSON terminology, there could be confustion between `legalIdentifier` and `identifier` (as of now these two peacefully coexist in the standard). `registryCode` is a better name for `legalIdentifier`. Other possibilities:

- registry
- localRegistryCode
- localBusinessRegistryCode

**Comment by kostysh** [comment]
implemented in version 0.4.3
